### ISSUE TITLE
Error: error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by TimoPeraza** [fastruby/create-heroku-review-app#5]
I have this issue trying to deploy it to heroku:

```
       ncc: Compiling file index.js into CJS
       Error: error:0308010C:digital envelope routines::unsupported
           at new Hash (node:internal/crypto/hash:79:19)
           at Object.createHash (node:crypto:139:10)
           at hashOf (/tmp/build_52876875/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:37:1855992)
           at ncc (/tmp/build_52876875/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:37:1860457)
           at runCmd (/tmp/build_52876875/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:55128)
           at 819 (/tmp/build_52876875/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:51698)
           at __webpack_require__ (/tmp/build_52876875/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:59048)
           at /tmp/build_52876875/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:59260
           at /tmp/build_52876875/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:59321
           at Object.<anonymous> (/tmp/build_52876875/node_modules/@vercel/ncc/dist/ncc/cli.js:8:28) {
         opensslErrorStack: [
           'error:03000086:digital envelope routines::initialization error',
           'error:0308010C:digital envelope routines::unsupported'
         ],
         library: 'digital envelope routines',
         reason: 'unsupported',
         code: 'ERR_OSSL_EVP_UNSUPPORTED'
       }
```

**Comment by etagwerker** [comment]
@TimoPeraza This error does not seem to be related with this project. It seems to be an issue when you compile `index.js`
